global:
  scrape_interval: 15s      # 15초마다 메트릭 수집
  evaluation_interval: 15s  # 15초마다 규칙 평가

scrape_configs:
  - job_name: 'spring-boot-app'                 # 스프링 부트 애플리케이션 작업 이름
    metrics_path: '/actuator/prometheus'        # 메트릭 경로
    static_configs:
      - targets: ['api:8080']                   # docker-compose.yml에서의 서비스 이름 'api'

  - job_name: 'prometheus'                      # Prometheus 자체 모니터링
    static_configs:
      - targets: ['localhost:9090']